// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["backbone", "mustache", "text!templates/shared/sniDropDowns.htm", "collections/sniHeads"], function(backbone, mustache, template, SniHeads) {
    var SniCascadingDropDown;
    return SniCascadingDropDown = (function(_super) {

      __extends(SniCascadingDropDown, _super);

      function SniCascadingDropDown() {
        return SniCascadingDropDown.__super__.constructor.apply(this, arguments);
      }

      SniCascadingDropDown.prototype._wireUpDropDowns = function() {
        return $("#heads").change(function() {
          var items;
          items = $(this).find(":selected").data("items");
          if ((items != null) !== void 0) {
            $("#items").show().find("option").remove();
            return $.each(items, function(index, item) {
              var $option;
              $option = $("<option>").text(item.Title).val(item.SniNo);
              return $("#items").append($option);
            });
          }
        });
      };

      SniCascadingDropDown.prototype.initialize = function() {
        return this.collection = new SniHeads();
      };

      SniCascadingDropDown.prototype.render = function() {
        var _this = this;
        console.log('todo,refactor');
        this.collection.fetch({
          success: function() {
            return _this.collection.each(function(sniHead) {
              var $option;
              sniHead = sniHead.toJSON();
              $option = $("<option>").text(sniHead.Title).val(sniHead.SniHeadId).data("items", sniHead.Items);
              return $("#heads").append($option);
            });
          }
        });
        this.$el.html(template);
        return this._wireUpDropDowns();
      };

      SniCascadingDropDown.prototype.getHeadVal = function() {
        return $('#heads').val();
      };

      SniCascadingDropDown.prototype.getItemVal = function() {
        return $('#items').val();
      };

      return SniCascadingDropDown;

    })(backbone.View);
  });

}).call(this);
