//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Yoyyin.Data.Core;
using Yoyyin.Data.Core.Entities;


namespace Yoyyin.Data
{
    public partial class Answer : IAnswer
    {
        #region Primitive Properties
    
        public virtual int AnswerID
        {
            get;
            set;
        }
    
        public virtual System.Guid UserId
        {
            get { return _userId; }
            set
            {
                if (_userId != value)
                {
                    if (User != null && User.UserId != value)
                    {
                        User = null;
                    }
                    _userId = value;
                }
            }
        }
        private System.Guid _userId;
    
        public virtual int QuestionID
        {
            get { return _questionID; }
            set
            {
                if (_questionID != value)
                {
                    if (Question != null && Question.QuestionID != value)
                    {
                        Question = null;
                    }
                    _questionID = value;
                }
            }
        }
        private int _questionID;
    
        public virtual System.DateTime Created
        {
            get;
            set;
        }
    
        public virtual string Text
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual IQuestion Question
        {
            get { return _question; }
            set
            {
                if (!ReferenceEquals(_question, value))
                {
                    var previousValue = _question;
                    _question = value;
                    FixupQuestion(previousValue);
                }
            }
        }
        private IQuestion _question;
    
        public virtual IUser User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private IUser _user;

        #endregion
        #region Association Fixup
    
        private void FixupQuestion(IQuestion previousValue)
        {
            if (previousValue != null && previousValue.Answer.Contains(this))
            {
                previousValue.Answer.Remove(this);
            }
    
            if (Question != null)
            {
                if (!Question.Answer.Contains(this))
                {
                    Question.Answer.Add(this);
                }
                if (QuestionID != Question.QuestionID)
                {
                    QuestionID = Question.QuestionID;
                }
            }
        }
    
        private void FixupUser(IUser previousValue)
        {
            if (previousValue != null && previousValue.Answer.Contains(this))
            {
                previousValue.Answer.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.Answer.Contains(this))
                {
                    User.Answer.Add(this);
                }
                if (UserId != User.UserId)
                {
                    UserId = User.UserId;
                }
            }
        }

        #endregion
    }
}
