//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Yoyyin.Data.Core;
using Yoyyin.Data.Core.Entities;


namespace Yoyyin.Data
{
    public partial class Comment : IComment
    {
        #region Primitive Properties
    
        public virtual System.Guid UserId
        {
            get { return _userId; }
            set
            {
                if (_userId != value)
                {
                    if (User != null && User.UserId != value)
                    {
                        User = null;
                    }
                    _userId = value;
                }
            }
        }
        private System.Guid _userId;
    
        public virtual System.Guid CommentUserId
        {
            get { return _commentUserId; }
            set
            {
                if (_commentUserId != value)
                {
                    if (User1 != null && User1.UserId != value)
                    {
                        User1 = null;
                    }
                    _commentUserId = value;
                }
            }
        }
        private System.Guid _commentUserId;
    
        public virtual string Text
        {
            get;
            set;
        }
    
        public virtual System.DateTime Created
        {
            get;
            set;
        }
    
        public virtual int CommentID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CommentCommentID
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual IUser User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private IUser _user;
    
        public virtual IUser User1
        {
            get { return _user1; }
            set
            {
                if (!ReferenceEquals(_user1, value))
                {
                    var previousValue = _user1;
                    _user1 = value;
                    FixupUser1(previousValue);
                }
            }
        }
        private IUser _user1;

        #endregion
        #region Association Fixup
    
        private void FixupUser(IUser previousValue)
        {
            if (previousValue != null && previousValue.Comment.Contains(this))
            {
                previousValue.Comment.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.Comment.Contains(this))
                {
                    User.Comment.Add(this);
                }
                if (UserId != User.UserId)
                {
                    UserId = User.UserId;
                }
            }
        }
    
        private void FixupUser1(IUser previousValue)
        {
            if (previousValue != null && previousValue.Comment1.Contains(this))
            {
                previousValue.Comment1.Remove(this);
            }
    
            if (User1 != null)
            {
                if (!User1.Comment1.Contains(this))
                {
                    User1.Comment1.Add(this);
                }
                if (CommentUserId != User1.UserId)
                {
                    CommentUserId = User1.UserId;
                }
            }
        }

        #endregion
    }
}
