//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Yoyyin.Data.Core;
using Yoyyin.Data.Core.Entities;


namespace Yoyyin.Data
{
    public partial class Message : IMessage
    {
        #region Primitive Properties
    
        public virtual System.Guid FromUserId
        {
            get { return _fromUserId; }
            set
            {
                if (_fromUserId != value)
                {
                    if (User != null && User.UserId != value)
                    {
                        User = null;
                    }
                    _fromUserId = value;
                }
            }
        }
        private System.Guid _fromUserId;
    
        public virtual System.Guid ToUserId
        {
            get { return _toUserId; }
            set
            {
                if (_toUserId != value)
                {
                    if (User1 != null && User1.UserId != value)
                    {
                        User1 = null;
                    }
                    _toUserId = value;
                }
            }
        }
        private System.Guid _toUserId;
    
        public virtual string FromMessage
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Created
        {
            get;
            set;
        }
    
        public virtual string Subject
        {
            get;
            set;
        }
    
        public virtual int MessageID
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual IUser User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private IUser _user;
    
        public virtual IUser User1
        {
            get { return _user1; }
            set
            {
                if (!ReferenceEquals(_user1, value))
                {
                    var previousValue = _user1;
                    _user1 = value;
                    FixupUser1(previousValue);
                }
            }
        }
        private IUser _user1;

        #endregion
        #region Association Fixup
    
        private void FixupUser(IUser previousValue)
        {
            if (previousValue != null && previousValue.Message.Contains(this))
            {
                previousValue.Message.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.Message.Contains(this))
                {
                    User.Message.Add(this);
                }
                if (FromUserId != User.UserId)
                {
                    FromUserId = User.UserId;
                }
            }
        }
    
        private void FixupUser1(IUser previousValue)
        {
            if (previousValue != null && previousValue.Message1.Contains(this))
            {
                previousValue.Message1.Remove(this);
            }
    
            if (User1 != null)
            {
                if (!User1.Message1.Contains(this))
                {
                    User1.Message1.Add(this);
                }
                if (ToUserId != User1.UserId)
                {
                    ToUserId = User1.UserId;
                }
            }
        }

        #endregion
    }
}
