//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Yoyyin.Data.Core;
using Yoyyin.Data.Core.Entities;


namespace Yoyyin.Data
{
    public partial class SniItem : ISniItem
    {
        #region Primitive Properties
    
        public virtual string SniNo
        {
            get;
            set;
        }
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual string SniHeadID
        {
            get { return _sniHeadID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_sniHeadID != value)
                    {
                        if (SniHead != null && SniHead.SniHeadID != value)
                        {
                            SniHead = null;
                        }
                        _sniHeadID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private string _sniHeadID;

        #endregion
        #region Navigation Properties
    
        public virtual ISniHead SniHead
        {
            get { return _sniHead; }
            set
            {
                if (!ReferenceEquals(_sniHead, value))
                {
                    var previousValue = _sniHead;
                    _sniHead = value;
                    FixupSniHead(previousValue);
                }
            }
        }
        private ISniHead _sniHead;
    
        public virtual ICollection<User> User
        {
            get
            {
                if (_user == null)
                {
                    var newCollection = new FixupCollection<User>();
                    newCollection.CollectionChanged += FixupUser;
                    _user = newCollection;
                }
                return _user;
            }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user as FixupCollection<User>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupUser;
                    }
                    _user = value;
                    var newValue = value as FixupCollection<User>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupUser;
                    }
                }
            }
        }
        private ICollection<User> _user;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupSniHead(ISniHead previousValue)
        {
            if (previousValue != null && previousValue.SniItem.Contains(this))
            {
                previousValue.SniItem.Remove(this);
            }
    
            if (SniHead != null)
            {
                if (!SniHead.SniItem.Contains(this))
                {
                    SniHead.SniItem.Add(this);
                }
                if (SniHeadID != SniHead.SniHeadID)
                {
                    SniHeadID = SniHead.SniHeadID;
                }
            }
            else if (!_settingFK)
            {
                SniHeadID = null;
            }
        }
    
        private void FixupUser(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (User item in e.NewItems)
                {
                    item.SniItem = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (User item in e.OldItems)
                {
                    if (ReferenceEquals(item.SniItem, this))
                    {
                        item.SniItem = null;
                    }
                }
            }
        }

        #endregion
    }
}
