// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["backbone"], function(backbone) {
    var CurrentUser;
    CurrentUser = (function(_super) {

      __extends(CurrentUser, _super);

      function CurrentUser() {
        return CurrentUser.__super__.constructor.apply(this, arguments);
      }

      CurrentUser.prototype.urlRoot = "/CurrentUser";

      CurrentUser.prototype.initialize = function() {
        return this.on("all", function(e) {
          return console.log(e);
        });
      };

      return CurrentUser;

    })(backbone.Collection);
    return {
      getImageSrc: function() {
        var _ref;
        return (_ref = this.get("HasImage")) != null ? _ref : "/Content/Upload/Images/" + this.id + {
          ".jpg": "/Images/glyphicons_003_user@2x.png"
        };
      }
    };
  });

}).call(this);
