// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["backbone"], function(backbone) {
    var User;
    return User = (function(_super) {

      __extends(User, _super);

      function User() {
        return User.__super__.constructor.apply(this, arguments);
      }

      User.prototype.initialize = function() {
        return this.on('all', function(e) {
          return console.log(e);
        });
      };

      User.prototype.urlRoot = function() {
        return "/User/";
      };

      User.prototype.defaults = {
        Created: new Date()
      };

      User.prototype.Name = '';

      User.prototype.CVFileName = '';

      User.prototype.Active = true;

      User.prototype.UserTypeDescription = '';

      User.prototype.Address = {
        Coordinate: {
          Latitude: null,
          Longitude: null
        }
      };

      User.prototype.Settings = {};

      User.prototype.Email = '';

      User.prototype.UserType = 0;

      User.prototype.Urls = [];

      User.prototype.Ideas = [
        {
          SearchProfile: {},
          Funding: {},
          Comments: []
        }
      ];

      User.prototype.Competences = [];

      User.prototype.Image = {
        HasImage: false,
        Avatar: ''
      };

      User.prototype.Presentation = '';

      User.prototype.LookingFor = {};

      return User;

    })(backbone.Model);
  });

}).call(this);
