// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["backbone"], function(backbone) {
    var User;
    return User = (function(_super) {

      __extends(User, _super);

      function User() {
        return User.__super__.constructor.apply(this, arguments);
      }

      User.prototype.initialize = function() {
        return this.on('all', function(e) {
          return console.log(e);
        });
      };

      User.prototype.urlRoot = function() {
        return "/User/";
      };

      User.prototype.defaults = {
        Name: '',
        CVFileName: '',
        Active: true,
        UserTypeDescription: '',
        Address: {
          Coordinate: {
            Latitude: null,
            Longitude: null
          }
        },
        Settings: {},
        Email: '',
        UserType: 0,
        Urls: [],
        Ideas: [
          {
            SearchProfile: {},
            Funding: {},
            Comments: []
          }
        ],
        Competences: [],
        Image: {
          HasImage: false,
          Avatar: ''
        },
        Presentation: '',
        LookingFor: {}
      };

      return User;

    })(backbone.Model);
  });

}).call(this);
