// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["views/registration/step", "text!templates/registration/idea.htm", "views/shared/sniCascadingDropDown", "views/shared/tags/competences", "views/shared/tags/searchWords"], function(StepView, template, CascadingDropDownView, CompetencesTagsView, SearchWordsTagsView) {
    var Idea;
    return Idea = (function(_super) {

      __extends(Idea, _super);

      function Idea() {
        return Idea.__super__.constructor.apply(this, arguments);
      }

      Idea.prototype.render = function() {
        var competencesTagsView, searchWordsTagsView;
        this.setHero({
          Headline: "Sista steget - Nu vill vi höra om din affärsidé"
        });
        this.appendButtons({
          markup: template,
          previousStep: "upload",
          nextStep: "idea"
        });
        $("div.form-actions").append("<a class='btn btn-warning' href='/#/register/userType'>Jag har ingen affärsidé</a>");
        this.dropDown = new CascadingDropDownView({
          el: $("#sniDropDowns")
        });
        this.dropDown.render();
        competencesTagsView = new CompetencesTagsView({
          el: $("#competencesNeeded")
        });
        competencesTagsView.render();
        searchWordsTagsView = new SearchWordsTagsView({
          el: $("#tags")
        });
        return searchWordsTagsView.render();
      };

      Idea.prototype._getTags = function(id) {
        return $("#" + id).tagit('assignedTags');
      };

      Idea.prototype.saveStep = function() {
        var idea, ideas;
        ideas = this.model.get("Ideas");
        idea = ideas[0];
        idea.CompanyName = this.$el.find('#companyName').val();
        idea.Title = this.$el.find('#title').val();
        idea.Description = this.$el.find('#description').val();
        idea.SniNo = this.dropDown.getHeadVal();
        idea.SniHeadId = this.dropDown.getItemVal();
        idea.SearchProfile.CompetencesNeeded = this._getTags('competencesNeeded');
        idea.SearchWords = this._getTags('tags');
        console.log(this.model.toJSON().Ideas[0]);
        this.model.save();
        return location.href = '/FirstSignIn';
      };

      return Idea;

    })(StepView);
  });

}).call(this);
