// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["views/registration/step", "views/shared/tags/competences", "views/shared/tags/searchWords", "text!templates/registration/tags.htm"], function(StepView, CompetencesTagsView, SearchWordsTagsView, template) {
    var Tags;
    return Tags = (function(_super) {

      __extends(Tags, _super);

      function Tags() {
        return Tags.__super__.constructor.apply(this, arguments);
      }

      Tags.prototype.render = function() {
        var competencesTagsView, searchWordsTagsView;
        this.setHero({
          Headline: "Vilka kompetenser söker du?"
        });
        this.appendButtons({
          markup: template,
          previousStep: "userTypesNeeded",
          nextStep: "upload"
        });
        competencesTagsView = new CompetencesTagsView({
          el: $("#competencesNeeded")
        });
        competencesTagsView.render();
        searchWordsTagsView = new SearchWordsTagsView({
          el: $("#tags")
        });
        return searchWordsTagsView.render();
      };

      return Tags;

    })(StepView);
  });

}).call(this);
