// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["views/registration/step", "text!templates/registration/upload.htm"], function(StepView, template) {
    var Upload;
    return Upload = (function(_super) {

      __extends(Upload, _super);

      function Upload() {
        return Upload.__super__.constructor.apply(this, arguments);
      }

      Upload.prototype.render = function() {
        this.setHero({
          Headline: "Bild och CV"
        });
        this.appendButtons({
          markup: template,
          previousStep: "tags",
          nextStep: "idea"
        });
        return $('.btn-group').find('btn').button();
      };

      Upload.prototype.saveStep = function() {
        return console.log('To implement');
      };

      return Upload;

    })(StepView);
  });

}).call(this);
