// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["views/registration/step", "text!templates/registration/wanted.htm"], function(StepView, template) {
    var Wanted;
    return Wanted = (function(_super) {

      __extends(Wanted, _super);

      function Wanted() {
        return Wanted.__super__.constructor.apply(this, arguments);
      }

      Wanted.prototype.render = function() {
        this.setHero({
          Headline: "Vad söker du?"
        });
        this.appendButtons({
          markup: template,
          previousStep: "personalInfo",
          nextStep: "location"
        });
        return $("#wantsFinancing").change(function() {
          return $("#financing").toggle();
        });
      };

      Wanted.prototype.save = function() {
        var lookingFor;
        lookingFor = {
          JoinOrBeJoined: $("#JoinOrBeJoined").is(":checked"),
          PartnerToMyIdea: $("#PartnerToMyIdea").is(":checked"),
          IdeasToJoin: $("#IdeasToJoin").is(":checked"),
          Investements: $("#Investments").is(":checked"),
          Financing: $("#Financing").is(":checked")
        };
        this.model.set("LookingFor", lookingFor);
        return console.log(this.model.toJSON());
      };

      return Wanted;

    })(StepView);
  });

}).call(this);
