// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["backbone"], function(backbone) {
    var Messages;
    return Messages = (function(_super) {

      __extends(Messages, _super);

      function Messages() {
        return Messages.__super__.constructor.apply(this, arguments);
      }

      Messages.prototype.url = "/Messages/GetAll";

      Messages.prototype.initialize = function() {
        return this.fetch();
      };

      return Messages;

    })(backbone.Collection);
  });

}).call(this);
