// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["backbone"], function(backbone) {
    var SniHeads;
    return SniHeads = (function(_super) {

      __extends(SniHeads, _super);

      function SniHeads() {
        return SniHeads.__super__.constructor.apply(this, arguments);
      }

      SniHeads.prototype.url = "/SniHeads";

      return SniHeads;

    })(backbone.Collection);
  });

}).call(this);
