// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["backbone", "models/userType"], function(backbone, UserTypeModel) {
    var UserTypes;
    return UserTypes = (function(_super) {

      __extends(UserTypes, _super);

      function UserTypes() {
        return UserTypes.__super__.constructor.apply(this, arguments);
      }

      UserTypes.prototype.url = "/UserTypes";

      UserTypes.prototype.model = UserTypeModel;

      return UserTypes;

    })(backbone.Collection);
  });

}).call(this);
