// Generated by CoffeeScript 1.3.3
(function() {

  define('mustache', ['../lib/mustache'], function() {
    return Mustache;
  });

  require.config({
    baseUrl: "/Scripts/yoyyin",
    paths: {
      "underscore": "../lib/underscore",
      "backbone": "../lib/backbone"
    },
    'shim': {
      backbone: {
        'deps': ['jquery', 'underscore'],
        'exports': 'Backbone'
      }
    }
  });

  $(function() {
    $("#formQuickSearch").quickSearch({
      $placeHolder: $("#sectionMainContent")
    });
    return $('#carousel').carousel();
  });

  require(["backbone", "routers/router", "views/currentUser/dashboard", "views/currentUser/userBox", "views/currentUser/navigation", "models/currentUser"], function(backbone, Router, DashboardView, UserBox, NavigationView, CurrentUserModel) {
    var currentUser, router;
    currentUser = new CurrentUserModel;
    currentUser.fetch({
      success: function() {
        var dashboard, navigation, userBox;
        userBox = new UserBox({
          model: currentUser,
          el: $("#userBox")
        });
        userBox.render;
        dashboard = new DashboardView({
          model: currentUser,
          el: $("#body")
        });
        dashboard.render;
        navigation = new NavigationView({
          el: $("#subMenu"),
          model: currentUser
        });
        return navigation.render();
      }
    });
    router = new Router();
    return backbone.history.start();
  });

}).call(this);
