// Generated by CoffeeScript 1.3.3
(function() {

  define('mustache', ['../lib/mustache'], function() {
    return Mustache;
  });

  require.config({
    baseUrl: "/Scripts/yoyyin",
    paths: {
      "underscore": "../lib/underscore",
      "backbone": "../lib/backbone"
    },
    'shim': {
      backbone: {
        'deps': ['jquery', 'underscore'],
        'exports': 'Backbone'
      }
    }
  });

  require(['backbone', "routers/registrationRouter"], function(backbone, Router) {
    var router;
    router = new Router();
    return backbone.history.start();
  });

}).call(this);
