// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["backbone", "mustache", "models/currentUser", "text!templates/shared/modal.htm", "text!templates/user/newMessage.htm", "text!templates/user/image.htm"], function(backbone, mustache, CurrentUserModel, modalTemplate, newMessageTemplate, imageTemplate) {
    var NewMessage;
    return NewMessage = (function(_super) {

      __extends(NewMessage, _super);

      function NewMessage() {
        return NewMessage.__super__.constructor.apply(this, arguments);
      }

      NewMessage.prototype.render = function() {
        var body, imageMarkup, markup;
        imageMarkup = mustache.render(imageTemplate, {
          Src: that.model.toJSON().ProfileImageSrc
        });
        body = mustache.render(newMessageTemplate, {
          imageMarkup: imageMarkup
        });
        markup = mustache.render(modalTemplate, {
          title: "Nytt meddelande",
          body: body,
          actionText: "Skicka"
        });
        return $(markup).modal("show");
      };

      return NewMessage;

    })(backbone.View);
  });

}).call(this);
