// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["underscore", "backbone", "mustache", "text!../../../../Templates/Member/User/image.htm"], function(_, Backbone, mustache, imageTemplate) {
    var UserThumbnail;
    return UserThumbnail = (function(_super) {

      __extends(UserThumbnail, _super);

      function UserThumbnail() {
        return UserThumbnail.__super__.constructor.apply(this, arguments);
      }

      UserThumbnail.prototype.render = function() {
        var user;
        user = this.model.toJSON();
        return this.$el.html(mustache.render(imageTemplate, user));
      };

      return UserThumbnail;

    })(Backbone.View);
  });

}).call(this);
